### ISSUE TITLE
Call to undefined function Unirest\curl_init()

### ISSUE THREAD

**Issue by Slauf21** [danger89/metacritic_api#10]
Hey

When I call matecritic.php I get this fatal error: Call to undefined function Unirest\curl_init(). I have the php_curl.dll file under my php extensions. Ive also added my php directory in the system variable "path". I should probably note that im trying to call this script from a c++ program.

Could you maybe help me with this?

**Comment by danger89** [comment]
It's important to first install all dependencies using composer.

**Comment by danger89** [comment]
Did you also try example.php?

**Comment by Slauf21** [comment]
Im using php in command line. For now, all my c++ program does is simulate a command line. It calls example.php and passes an argument (game name) to the script and should receive the JSON output echo. I have the following version of php installed: PHP 8.1.4 (cli) (built: Mar 16 2022 09:32:18) (NTS Visual C++ 2019 x64).

**Comment by danger89** [comment]
OK. So I can't reproduce the problem on my Linux machine with PHP cli. So PHP 8 should work.

The only option would be that curl is not enabled. Did you remove the semi-colon(`;`)  in front of the `extension=php_curl.dll` line?

**Comment by danger89** [comment]
You can validate whether cURL is enabled or not in PHP using and check the output:

```php
<?php
phpinfo();
?>
```
Add this content to a `phpinfo.php` file for example.

**Comment by Slauf21** [comment]
I have a php.ini-development file and a php.ini-production file. `extension=php_curl.dll` was absent in both files so i just added it myself. There was a line in both files `;extension=curl` and I removed the `;` in both. The result is the same. I executed the `phpinfo()` and there is only one instance of curl mentioned: 
![image](https://user-images.githubusercontent.com/79916416/161962971-3135d67f-2aec-4121-83e9-3b3cc81bad27.png). Its not like your output even tough I removed the `;` .

**Comment by danger89** [comment]
> I have a php.ini-development file and a php.ini-production file. `extension=php_curl.dll` was absent in both files so i just added it myself. There was a line in both files `;extension=curl` and I removed the `;` in both. The result is the same. I executed the `phpinfo()` and there is only one instance of curl mentioned: ![image](https://user-images.githubusercontent.com/79916416/161962971-3135d67f-2aec-4121-83e9-3b3cc81bad27.png). Its not like your output even tough I removed the `;` .

You are using windows right? Do not enable this other line please. That is for Linux only. Only apply the extension lines with dll at the end.

**Comment by Slauf21** [comment]
I think I managed to solve it.
![image](https://user-images.githubusercontent.com/79916416/161966122-8da2117a-b85c-400a-a55f-2f50727c7f59.png)
`Loaded Configuration File =>` was empty, so I just changed the php.ini-development file to php.ini. Now I dont get this error anymore.

**Comment by danger89** [comment]
Ah great. Good job.
