### ISSUE TITLE
Fatal error: Class 'MetacriticAPI' not found

### ISSUE THREAD

**Issue by felmur** [danger89/metacritic_api#6]
Hi,

I've installed the directory metacritic_api in the root of my website.

So, i call example.php from browser:

https://mywebsite/metacritic_api/example.php.

The results is:
Fatal error: Uncaught Error: Class 'MetacriticAPI' not found in /srv/http/metacritic_api/example.php:7 Stack trace: #0 {main} thrown in /srv/http/metacritic_api/example.php on line 7

Where am I doing wrong?

Regards.

**Comment by danger89** [comment]
Are you sure you did put `metacritic.php` next to the example.php file?

**Comment by danger89** [comment]
You could try: `new MetacriticAPI\MetacriticAPI()` on line 7: https://github.com/danger89/metacritic_api/blob/master/example.php#L7

**Comment by felmur** [comment]
> Are you sure you did put `metacritic.php` next to the example.php file?

yes, files metacritic.php and example.php are in the same directory

> You could try: `new MetacriticAPI\MetacriticAPI()` on line 7: 

[felice@asus metacritic_api]$ ls
composer.json  example.php  LICENSE         phpcs.xml        psalm.xml
composer.lock  libs         metacritic.php  phpmetrics.json  README.md

==========> this is output with normal line 7
```
[felice@asus metacritic_api]$ php example.php 
PHP Fatal error:  Uncaught Error: Class 'MetacriticAPI' not found in /srv/http/metacritic_api/example.php:7
Stack trace:
#0 {main}
  thrown in /srv/http/metacritic_api/example.php on line 7

Fatal error: Uncaught Error: Class 'MetacriticAPI' not found in /srv/http/metacritic_api/example.php:7
Stack trace:
#0 {main}
  thrown in /srv/http/metacritic_api/example.php on line 7
```

==========> now I edit example.php file how you suggested
`[felice@asus metacritic_api]$ vi example.php 
`
==========> this is output now
```
[felice@asus metacritic_api]$ php example.php 
PHP Fatal error:  Uncaught Error: Class 'MetacriticAPI\Unirest\Request' not found in /srv/http/metacritic_api/metacritic.php:36
Stack trace:
#0 /srv/http/metacritic_api/example.php(8): MetacriticAPI\MetacriticAPI->getMetacriticPage('the-elder-scrol...')
#1 {main}
  thrown in /srv/http/metacritic_api/metacritic.php on line 36


Fatal error: Uncaught Error: Class 'MetacriticAPI\Unirest\Request' not found in /srv/http/metacritic_api/metacritic.php:36
Stack trace:
#0 /srv/http/metacritic_api/example.php(8): MetacriticAPI\MetacriticAPI->getMetacriticPage('the-elder-scrol...')
#1 {main}
  thrown in /srv/http/metacritic_api/metacritic.php on line 36
```

**Comment by danger89** [comment]
OK, I indeed fixed the namespace issues. Next problem is that Metacritics changes their site.

**Comment by felmur** [comment]
Now it works and you are right: the result of the value of users and metascore is always 0 and a lot of json result is empty.

**Comment by danger89** [comment]
That is what I said.. The next problem was that https://www.metacritic.com changed their site..

Anyway, in the meanwhile I fixed that myself, see master branch again.
