### ISSUE TITLE
Class 'MetacriticAPI' not found

### ISSUE THREAD

**Issue by gnicolas31** [danger89/metacritic_api#8]
Hi,

I put my test file aside the metacritic.php with all the libs in correct place bt I can't got it work , I have this error : 

`Class 'MetacriticAPI' not found in /homepages/28/d848108401/htdocs/cron/metacritic/example.php:7`

can you help me ?

**Comment by danger89** [comment]
Try to add the following line above the include in the example.php file:

`namespace MetacriticAPI;`

**Comment by gnicolas31** [comment]
Hi danger89 ! Thank's a lot for this solution ! I have a new error now : 

`Class 'MetacriticAPI\Unirest\Request' not found in /homepages/28/d848108401/htdocs/cron/metacritic/metacritic.php:`

maybe I need to do something with unirest ?

**Comment by gnicolas31** [comment]
Herm sadly I don't know what to do :/ There is no way to solve this problem ? :/

**Comment by danger89** [comment]
I think I fixed it all.

Please get the latest code from master branch:

```sh
git reset --hard
git pull
```

Working example:
https://test.melroy.org/example.php
